[package]
name = "rosc"
version = "0.1.4"
authors = ["Andreas Linz <klingt.net@gmail.com>"]
description = "An OSC library for Rust"
keywords = ["audio", "osc"]
documentation = "https://docs.klingt.net/rustdoc/rosc"
repository = "https://git.klingt.net/alinz/rosc"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
byteorder = "^0.3"
clippy = "^0"
